# Originated from https://github.com/bitnami/bitnami-docker-kafka/blob/0b1b18843b8a5c754a4c6e52a49ac5cf992fa5ed/docker-compose.yml
version: '3'

services:
  datagen:
    build: .
    depends_on:
      - connect

  sut:
    build: ./test
    depends_on:
      - kafka

  connect:
    image: leonardobonacci/apache-kafka-connect:2.8.0
    build: ./connect
    depends_on:
      - kafka
    ports:
      - '8083:8083'
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-jib
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092

      CONNECT_GROUP_ID: cg_connect-idea
      CONNECT_CONFIG_STORAGE_TOPIC: connect-jib_config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-jib_offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-jib_status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter

      CONNECT_PLUGIN_PATH: /app/libs

  zookeeper:
    image: bitnami/zookeeper:3.6.2-debian-10-r186
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.0-debian-10-r7
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=48  # 2 days of retention for demo purposes
      # https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
